### PR TITLE
Example for typed ambient modules

### PR DESCRIPTION
**Pull request by oliver-h**
I added a simple example for using mathjs with tsify. Unfortunately, I don't know how to tell tsify to include mathjs to the bundle. The typescript compiler won't complain and a bundle including the 2 simple test modules will be created, but mathjs is not included.

The command I used to create the bundle:
`browserify src/module2.ts typings/browser.d.ts -p [ tsify --noImplicitAny ] > bundle.js`

Thank you in advance!

### CODE REVIEW

**Comment by sebastianhaas** [comment]
Re-write your mathjs typings to something like https://gist.github.com/sebastianhaas/09598bb21921ac9acdef will fix the issue.

Then you can import and use it like
 ```javascript
import * as math from "mathjs";
let absolute: any = math.abs(-10);
```
which will make browserify bundle your dependencies correctly.

**Comment by sebastianhaas** [comment]
Any news on this @smrq?

**Comment by smrq** [comment]
I'm somewhat confused on what this is supposed to be showcasing.  The whole point of ambient typings is that the module is expected to exist at runtime (via e.g. an extra `<script>` tag).  If you want mathjs to be included in your bundle, then you shouldn't be using ambient typings.

I don't really want to include an example when I can't even determine what it's supposed to be an example of.

**Comment by oliver-h** [comment]
Actually what you say does make sense and I have to apologize - it seems that I just did not understand everything correctly (coming from a C# background there are quite a lot of new things to get into).

**Pull request closed without merging**
