### PR TITLE
Move fs.realpath from devDependencies to dependencies.

### PR DESCRIPTION
**Pull request by DirtyHairy**
Won't work otherwise if pulled in as a dependency :smirk:

### CODE REVIEW

**Comment by cartant** [comment]
Good spot. Thanks.

**Comment by cartant** [comment]
With some changes that I'm currently making, I'll need to move `semver`, too. So thanks again.

**Comment by DirtyHairy** [comment]
Tanks for the merge. Certainly a candidate for "fastest reaction ever" :smiley:

**Comment by cartant** [comment]
Just very glad that I didn't prepare a release a few days ago - only to have had it explode.

**Pull request merged**
