### PR TITLE
Added more logging

### PR DESCRIPTION
**Pull request by cartant**
@basarat When investigating the problem I had with the TypeScript 2.0.0 beta, I found it useful to add more logging. It's included in this PR.

### CODE REVIEW

**Comment by basarat** [comment]
Thanks. Is this log *always triggered* or driven by an option? (don't want to noise up users). Sorry for my lack of understanding if it is something obvious :rose:

**Comment by cartant** [comment]
No worries. It's just more logging that uses the standard [`debuglog`](https://nodejs.org/api/util.html#util_util_debuglog_section) mechanism that's in the current implementation. It's switched on using an environment variable. I usually specify it on the command line, like so:

    NODE_DEBUG=tsify browserify ... etc.

If the environment variable isn't defined or doesn't contain `tsify`, it's silent.

**Comment by basarat** [comment]
It seems its caused problems before. But I take your word for it and highly appreciate all you are doing for this project :rose: :100:. However I am not the project leader so all I can give you for now are lots of roses :heart: :heart_decoration: :rose: 

image

**Comment by cartant** [comment]
It's interesting that the changelog says it was removed in 0.15.0, because I only added it to the `index.js` file. It was already required in the `Tsifier.js` and `Host.js` files.

I guess if it was removed in 0.15.0, it was added back sometime later. If there are problems, I'll replace it with something like [this](https://github.com/visionmedia/debug).

My main reason for fixing things in this project is that I cannot stomach moving a configuration that builds 50+ modules from Browserify to WebPack - just because of waning TypeScript support in the former.

**Comment by cartant** [comment]
I suspect the changelog refers to the [removal of the `debuglog` NPM module](https://github.com/TypeStrong/tsify/blob/v0.14.8/package.json#L31), The current implementation uses Node's built-in [debuglog](https://nodejs.org/api/util.html#util_util_debuglog_section) function.

**Comment by basarat** [comment]
Thanks for digging that up. I added your tips to the docs : https://github.com/TypeStrong/tsify/blob/master/CONTRIBUTING.md#debugging :rose:

**Comment by blakeembrey** [comment]
Just a note, but `debuglog` does not exist on node 0.10 (so anyone doing tests there won't be able to update). That said, I don't know if this module previously support node 0.10 (and if it did, it should probably be part of Travis).

**Comment by cartant** [comment]
No worries. I, too, just looked it up. Seems like it was set to `>= 0.12` in [0.14.2](https://github.com/TypeStrong/tsify/blob/v0.14.2/package.json#L26-L28).

**Pull request merged**
