### PR TITLE
Explicitly use browserify entries

### PR DESCRIPTION
**Pull request by Freak613**
And again, saga about **includes**, in addition to https://github.com/TypeStrong/tsify/pull/183 and https://github.com/TypeStrong/tsify/issues/147.

My proposition is to explicitly specify list of files to compile based on browserify entries list.
It looks redundant to compile all files according to tsconfig.

If we have several bundles, now we can get errors unrelated to compiled bundle, if they are.
If we try to compile several bundles in one run, like I do in gulp with 
```
gulp.task("default", ["build-deps", "build"]);
```
It will compile all files twice, that is sensitive performance drawback.

### CODE REVIEW

**Comment by cartant** [comment]
I'm not in favour of overriding the `tsconfig.json` configuration by default. Also, this PR appears to effect some test failures.

However, I do have an alternative approach that should satisfy you and should resolve the issues you referenced. I'll give it some more thought and if it works, I'll prepare another release.

**Comment by dgreene1** [comment]
> However, I do have an alternative approach that should satisfy you and should resolve the issues you referenced. I'll give it some more thought and, if it works, I'll prepare another release.
@cartant any updates on this?

Because it's hard to consider using tsify with issues like https://github.com/TypeStrong/tsify/issues/147

**Comment by cartant** [comment]
@dgreene1 Yeah, it's been a long time since I posted that comment. My attention was diverted elsewhere and I didn't get back to this issue. I have the changes implemented in another [branch](https://github.com/cartant/tsify/commit/4f158263ac697c96f0b939386e4efd9f4af040be). I will have some time on Tuesday to review them, merge them and publish another release.

#147 pre-dates my time as a maintainer for this project. The author made a comment [here](https://github.com/TypeStrong/tsify/issues/143#issuecomment-220395731), that's relevant to the issue.

After I merge the changes, I will update the documentation. Now that the options in the `tsconfig.json` allow for more precise inclusions and exclusions, I think this is less of an issue. And with the change you will be able to override those options in the tsify configuration.

**Comment by cartant** [comment]
I've merged the changes I made (last year) and it's now possible to override the TypeScript `files`, `excludes`, and `includes` options in the tsify config.

In particular, if you only want to use the Browserify entry points, you can specify `files` as an empty array - so there's no need to specify the entry points twice (once for Browserify and, again, for tsify).

**Pull request closed without merging**
